#!/usr/bin/env bash
# MPM run for case 260421_215235_ab3785 — generated by mpm_input_from_case.py
# SE (K-fixed): E_SE=1.53 GPa ν=0.49  (bulk K=25.5 GPa real-LPSC,
#   shear μ=0.5134 GPa = ×1.0 champion; from DEM E_eff 1.35 GPa),
#   press 0.3 GPa.  n_grid 256 → est ~89M points (budget 90M)
#   — kept tractable so the run FINISHES.  More SE resolution: regenerate with a higher
#   --max-points (heavier/slower) or edit --n-grid below.  If it OOMs, lower --n-grid / raise --gpu-mem.
set -uo pipefail
# ── 경로 자립: KIT = zip 푼 폴더(입력 csv), SCR = 레포 scripts/ (킷 폴더 또는 그 부모에서 탐색) ──
KIT="$(cd "$(dirname "$0")" && pwd)"
SCR=""; for c in "$KIT/scripts" "$KIT/../scripts"; do [ -d "$c" ] && SCR="$(cd "$c" && pwd)" && break; done
if [ -z "$SCR" ]; then
  echo "[run_mpm] ABORT — scripts/ 를 못 찾음: 레포 루트(또는 scripts 심링크 있는 폴더)에 킷을 푸세요."
  exit 1
fi
# ── scripts 자동 최신화 (kit-gen↔runtime 버전 스큐 방지 = "--x100 unrecognized" 재발 차단; 끄기 MPM_NO_PULL=1) ──
if [ -z "${MPM_NO_PULL:-}" ] && [ -d "$SCR/../.git" ]; then
  echo "[run_mpm] git pull --ff-only (scripts 최신화)…"
  ( cd "$SCR/.." && git pull --ff-only ) || echo "  ⚠ git pull 스킵 — 기존 스크립트로 진행 (필요시 수동 pull)"
fi
# ── one GPU = one run: GPU 경합 방지 (산출물 충돌은 아래 RUN_DIR 격리가 원천 차단).  MPM_FORCE=1 로 무시 ──
if [ -z "${MPM_DETACHED:-}" ] && [ -z "${MPM_FORCE:-}" ] && pgrep -f 'mpm3d_compaction.py' >/dev/null 2>&1; then
  echo "[run_mpm] ABORT — an MPM run is already active (pgrep mpm3d_compaction).  one GPU = one run."
  echo "          wait for FINAL / 'kill <PID>' first, or 'MPM_FORCE=1 bash run_mpm.sh' to override."
  exit 1
fi
# ── self-detach: an SSH drop must NOT kill the run (the foreground run kept dying on disconnect). ──
# ── RUN_DIR = 런 전용 폴더: 모든 산출물이 여기에만 쓰임 → 다른 킷/이전 런과 절대 안 섞이고
#    (2026-07-17 SBE↔DBE 루트-덮어쓰기·mv-레이스 사고 재발 방지), 진행 중 외부 정리 작업의
#    영향도 없음.  완료 시 $KIT/latest_run 심링크가 이 폴더를 가리킴. ──
if [ -z "${MPM_DETACHED:-}" ]; then
  export MPM_DETACHED=1
  export RUN_DIR="$KIT/run_VGCF1_PTFE1_$(date +%Y%m%d_%H%M%S)_$$"
  mkdir -p "$RUN_DIR"
  log="$RUN_DIR/mpm_run.log"
  echo "→ detached — survives SSH drop.  run dir: $RUN_DIR"
  setsid nohup bash "$0" "$@" >"$log" 2>&1 </dev/null &
  echo "   PID $!     follow: tail -f $log     stop: kill $!"
  exit 0
fi
cd "$RUN_DIR"
# ===== actual run (detached; all output → this run dir only) =====
echo "[run_mpm] $(hostname) start $(date)  n_grid=256  est_pts~89M  dir=$RUN_DIR"
# ── v3 열화-근접 옵션 (기본 안전 = 기존 convention 유지; §F1) ──────────────────────────────
#   MPM_FRACTURE=1        → 초기압밀 취성 crack-void (ASSUMED-FORM void frag0.15/pulv0.35; DEM=WHERE, MPM=형태)
#   MPM_PERIODIC_SIGMA=1  → STEP3 σ 측면 주기BC (bulk-RVE 정합; ⚠기존 corpus=절연벽 through-thickness → 전환 시 재run)
#   Joule 발열맵(#29) = 기본 ON (순수 진단 q∝|J|²/σ, σ/porosity 불변 → hot-spot '어디서 발열')
FRAC=()
if [ "${MPM_FRACTURE:-0}" = "1" ] && [ -f "$KIT/fracture_scaffold.csv" ]; then
  FRAC=(--fracture-scaffold "$KIT/fracture_scaffold.csv" --fracture-min-stage fragmentation)
  echo "[run_mpm] ★ MPM_FRACTURE=1 → 취성 crack-void 적용 (ASSUMED-FORM void; DEM 취성 위치 기반)"
fi
PSIG=(); [ "${MPM_PERIODIC_SIGMA:-0}" = "1" ] && { PSIG=(--periodic); echo "[run_mpm] ★ MPM_PERIODIC_SIGMA=1 → STEP3 σ 주기BC (bulk-RVE)"; }
# 1) plastic compaction of the REAL SE around the fixed AM scaffold (periodic x,y RVE = DEM 'boundary p p f')
python3 "$SCR/mpm3d_compaction.py" \
  --am-scaffold "$KIT/am_scaffold.csv" --se-dump "$KIT/se_scaffold.csv" --periodic \
  --lateral-box 0.05 --n-grid 256 --arch cuda --gpu-mem 28 --protocol hold --frames 150 \
  --e-se 1.53 --nu-se 0.49 --target-gpa 0.3 \
  --save-se se_dump.npy --save-dg se_dump_dg.npy --save-eps se_dump_eps.npy --save-metrics mpm_metrics.json \
  --add-recipe "VGCF:PTFE=1:1" --add-l-cv 0.4 --mixing thinky --coh-ptfe 0.10 --binder-opt-wt 1.5 --fibre-buckle --fibre-align 0.692 --dilate-z 1.0214 --save-phase phase.npy --save-fibre fibre.npy --save-fibre-dia fibre_dia.npy "${FRAC[@]}" \
  || { echo "[run_mpm] STEP 1 (compaction) FAILED — see the trace above.  NOT running the payload: it would"; \
        echo "          rebuild mpm_payload.json from the STALE se_dump.npy of a PREVIOUS run and report a"; \
        echo "          leftover porosity as if it were this run.  Fix the error and re-run."; exit 1; }
# 2) webapp payload (AM spheres + SE surface + seed/compacted + raw metrics)
#    + STEP3 σ_e 저항망 (전도상 voxel Kirchhoff, 풀해상도 — metrics.step3.sigma_e_eff + 입자별 je;
#      상대비교용 σ표는 metrics에 기록됨.  끄기: --no-step3)
python3 "$SCR/mpm_webapp_payload.py" \
  --se se_dump.npy --scaffold "$KIT/am_scaffold.csv" --se-dump "$KIT/se_scaffold.csv" \
  --n-vox 192 --tri-step 4 --smooth 1.5 --target-porosity 0.1905 --eps se_dump_eps.npy --dilate-z 1.0214 \
  --void-max 180000 --step3-vox 0.4 --field-max-points 90000 --step3-gpu --joule-heat "${PSIG[@]}" --metrics-json mpm_metrics.json --case 260421_215235_ab3785 --phase phase.npy --fibre fibre.npy --fibre-dia fibre_dia.npy --collector-rint 150 --collector-name SUS_bare_estimated --collector-scenario sus --save-step4-grid step4_grid.npz --out mpm_payload.json \
  || { echo "[run_mpm] STEP 2 (payload) FAILED — 압밀(se_dump.npy)은 무사하니 원인 수정 후 payload만 재실행:"; \
        echo "          cd $RUN_DIR && bash $KIT/step4_only.sh 는 STEP4용이고, payload는:"; \
        echo "          sed -n '/mpm_webapp_payload/,/--out mpm_payload.json/p' $KIT/run_mpm.sh > payload_only.sh && bash payload_only.sh"; \
        echo "          (흔한 원인: pip 모듈 누락 — python3 -m pip install scikit-image scipy)"; exit 1; }
# 3) STEP4-v2 — ★Zive 스케줄 9스텝 (Loop 전개 → 총 12런) 순차 (charge-first, per-step 컷오프).
#    ★v2 chaining ON: 각 스텝 = 직전 스텝 끝 셸-SOC에서 시작(연속 사이클, Loop 반복도 상태 누적); Rest = 실제 I=0 완화(REST-LOCAL); 실패 뒤 체인 스텝은 SKIP.  그리드는 STEP 2가 export.
# ★STEP4 솔버 노브 (2026-07-27 near-null 대수술; docs/step4_bottleneck_analysis_20260727.md)
#   기본값 = 권장값.  런타임 env 로 override 가능 (예: MPM_S4_CONTRAST_CAP=200 bash step4_only.sh).
#   prune_float: 집전체·AM 무접촉 부유 e-클러스터 제거 = 정확특이 블록 소거(해-불변, GPU-CG 회생)
#   ew        : Eisenstat-Walker inexact Newton (기본 OFF — 측정 2건서 일량 증가, 이득 미입증)
#   gpu_amg   : AMG apply 를 GPU V-cycle 미러로 (빌드는 CPU 1회; cupy 없으면 자동 CPU 폴백)
#   contrast_cap: e-망 σ대비 상한 (0=OFF).  200 → CG iter ×5.2 실측이나 σ_eff −7.8% →
#                 ★수렴 정체 시에만, 그리고 σ-메트릭 보고는 uncapped 런으로 (npz meta 에 태그됨)
export MPM_S4_PRUNE_FLOAT="${MPM_S4_PRUNE_FLOAT:-1}"
export MPM_S4_EW="${MPM_S4_EW:-0}"
export MPM_S4_GPU_AMG="${MPM_S4_GPU_AMG:-1}"
export MPM_S4_CONTRAST_CAP="${MPM_S4_CONTRAST_CAP:-200}"
echo "[run_mpm] STEP4 솔버: prune=$MPM_S4_PRUNE_FLOAT ew=$MPM_S4_EW gpu_amg=$MPM_S4_GPU_AMG cap=$MPM_S4_CONTRAST_CAP"
AP=""
for d in "$KIT/anchor_params" "$KIT/../anchor_params"; do [ -f "$d/ocp_nmc811_chen2020.csv" ] && AP="$d" && break; done
if [ -z "$AP" ]; then
  echo "[run_mpm] STEP4 SKIP — OCP 앵커 없음 (anchor_params/ocp_nmc811_chen2020.csv)."
  echo "          1회 생성: python3 $SCR/step4_pybamm_anchor.py --export-params   (pybamm 필요)"
  echo "          그 뒤 재개: bash step4_only.sh"
else
  rm -f s4state_*.npz   # 이전 시도 잔재가 SKIP 가드를 무력화(설정 혼합·stale 체인)하는 것 방지 — step4_only.sh 재실행은 체인을 처음부터 다시 돎
  echo "[run_mpm] STEP4 스케줄[0] 충전 0.2C (CV@4.3V I<0.1C cyc1 · ★풀셀 축: R_int=${MPM_S4_RINT:-50} Ωcm² 직렬 · ★SC 단결정 단일 D_s=3e-15 m²/s (mono, σ_e AM_S=10 mS/cm)) $(date)"
  python3 "$SCR/step4_dyn.py" --grid step4_grid.npz \
    --ocp-csv "$AP/ocp_nmc811_chen2020.csv" --params-json "$AP/params_nmc811_chen2020.json" \
    --c-rate 0.2 --charge --cv-hold --v-min 3 --v-max 4.3 --x100 0.9084 --i-cut-frac 0.1 --r-int-ohm-cm2 "${MPM_S4_RINT:-50}" --d-s "${MPM_S4_DS:-3e-15}" --save-state "s4state_00n1.npz" --gpu \
    --out "step4_sched00n1_chg_c0.2_rint${MPM_S4_RINT:-50}_ds${MPM_S4_DS:-3e-15}.npz" --viz-out "step4_sched00n1_viz_chg_c0.2_rint${MPM_S4_RINT:-50}_ds${MPM_S4_DS:-3e-15}.json" \
    || echo "[run_mpm] 스케줄[0]cyc1 충전 0.2C FAILED — 다음 스텝 계속"
  echo "[run_mpm] STEP4 스케줄[1]cyc1 Rest 1min (I=0 완화 REST-LOCAL, 체인) $(date)"
  if [ ! -f "s4state_00n1.npz" ]; then echo "[run_mpm] 스케줄[1]cyc1 SKIP — 체인 끊김(s4state_00n1.npz 없음; step4_only.sh 로 재개)"; else
  python3 "$SCR/step4_dyn.py" --grid step4_grid.npz \
    --ocp-csv "$AP/ocp_nmc811_chen2020.csv" --params-json "$AP/params_nmc811_chen2020.json" \
    --rest --t-rest-min 1 --x100 0.9084 --d-s "${MPM_S4_DS:-3e-15}" --init-state "s4state_00n1.npz" --save-state "s4state_01n1.npz" \
    --out "step4_sched01n1_rest.npz" \
    || echo "[run_mpm] 스케줄[1]cyc1 Rest FAILED — 다음 스텝 계속"
  fi
  echo "[run_mpm] STEP4 스케줄[2] 방전 0.2C (>=2.5V cyc1 · ★풀셀 축: R_int=${MPM_S4_RINT:-50} Ωcm² 직렬 · ★SC 단결정 단일 D_s=3e-15 m²/s (mono, σ_e AM_S=10 mS/cm)) $(date)"
  if [ ! -f "s4state_01n1.npz" ]; then echo "[run_mpm] 스케줄[2]cyc1 SKIP — 체인 끊김(s4state_01n1.npz 없음; step4_only.sh 로 재개)"; else
  python3 "$SCR/step4_dyn.py" --grid step4_grid.npz \
    --ocp-csv "$AP/ocp_nmc811_chen2020.csv" --params-json "$AP/params_nmc811_chen2020.json" \
    --c-rate 0.2 --v-min 2.5 --v-max 4.5 --x100 0.9084 --r-int-ohm-cm2 "${MPM_S4_RINT:-50}" --d-s "${MPM_S4_DS:-3e-15}" --init-state "s4state_01n1.npz" --save-state "s4state_02n1.npz" --gpu \
    --out "step4_sched02n1_c0.2_rint${MPM_S4_RINT:-50}_ds${MPM_S4_DS:-3e-15}.npz" --viz-out "step4_sched02n1_viz_c0.2_rint${MPM_S4_RINT:-50}_ds${MPM_S4_DS:-3e-15}.json" \
    || echo "[run_mpm] 스케줄[2]cyc1 방전 0.2C FAILED — 다음 스텝 계속"
  fi
  echo "[run_mpm] STEP4 스케줄[3]cyc1 Rest 1min (I=0 완화 REST-LOCAL, 체인) $(date)"
  if [ ! -f "s4state_02n1.npz" ]; then echo "[run_mpm] 스케줄[3]cyc1 SKIP — 체인 끊김(s4state_02n1.npz 없음; step4_only.sh 로 재개)"; else
  python3 "$SCR/step4_dyn.py" --grid step4_grid.npz \
    --ocp-csv "$AP/ocp_nmc811_chen2020.csv" --params-json "$AP/params_nmc811_chen2020.json" \
    --rest --t-rest-min 1 --x100 0.9084 --d-s "${MPM_S4_DS:-3e-15}" --init-state "s4state_02n1.npz" --save-state "s4state_03n1.npz" \
    --out "step4_sched03n1_rest.npz" \
    || echo "[run_mpm] 스케줄[3]cyc1 Rest FAILED — 다음 스텝 계속"
  fi
  echo "[run_mpm] STEP4 스케줄[4] 충전 2C (CV@4.3V I<1C cyc1 · ★풀셀 축: R_int=${MPM_S4_RINT:-50} Ωcm² 직렬 · ★SC 단결정 단일 D_s=3e-15 m²/s (mono, σ_e AM_S=10 mS/cm)) $(date)"
  if [ ! -f "s4state_03n1.npz" ]; then echo "[run_mpm] 스케줄[4]cyc1 SKIP — 체인 끊김(s4state_03n1.npz 없음; step4_only.sh 로 재개)"; else
  python3 "$SCR/step4_dyn.py" --grid step4_grid.npz \
    --ocp-csv "$AP/ocp_nmc811_chen2020.csv" --params-json "$AP/params_nmc811_chen2020.json" \
    --c-rate 2 --charge --cv-hold --v-min 3 --v-max 4.3 --x100 0.9084 --i-cut-frac 1 --r-int-ohm-cm2 "${MPM_S4_RINT:-50}" --d-s "${MPM_S4_DS:-3e-15}" --init-state "s4state_03n1.npz" --save-state "s4state_04n1.npz" --gpu \
    --out "step4_sched04n1_chg_c2_rint${MPM_S4_RINT:-50}_ds${MPM_S4_DS:-3e-15}.npz" --viz-out "step4_sched04n1_viz_chg_c2_rint${MPM_S4_RINT:-50}_ds${MPM_S4_DS:-3e-15}.json" \
    || echo "[run_mpm] 스케줄[4]cyc1 충전 2C FAILED — 다음 스텝 계속"
  fi
  echo "[run_mpm] STEP4 스케줄[5]cyc1 Rest 1min (I=0 완화 REST-LOCAL, 체인) $(date)"
  if [ ! -f "s4state_04n1.npz" ]; then echo "[run_mpm] 스케줄[5]cyc1 SKIP — 체인 끊김(s4state_04n1.npz 없음; step4_only.sh 로 재개)"; else
  python3 "$SCR/step4_dyn.py" --grid step4_grid.npz \
    --ocp-csv "$AP/ocp_nmc811_chen2020.csv" --params-json "$AP/params_nmc811_chen2020.json" \
    --rest --t-rest-min 1 --x100 0.9084 --d-s "${MPM_S4_DS:-3e-15}" --init-state "s4state_04n1.npz" --save-state "s4state_05n1.npz" \
    --out "step4_sched05n1_rest.npz" \
    || echo "[run_mpm] 스케줄[5]cyc1 Rest FAILED — 다음 스텝 계속"
  fi
  echo "[run_mpm] STEP4 스케줄[6] 방전 2C (>=2.5V cyc1 · ★풀셀 축: R_int=${MPM_S4_RINT:-50} Ωcm² 직렬 · ★SC 단결정 단일 D_s=3e-15 m²/s (mono, σ_e AM_S=10 mS/cm)) $(date)"
  if [ ! -f "s4state_05n1.npz" ]; then echo "[run_mpm] 스케줄[6]cyc1 SKIP — 체인 끊김(s4state_05n1.npz 없음; step4_only.sh 로 재개)"; else
  python3 "$SCR/step4_dyn.py" --grid step4_grid.npz \
    --ocp-csv "$AP/ocp_nmc811_chen2020.csv" --params-json "$AP/params_nmc811_chen2020.json" \
    --c-rate 2 --v-min 2.5 --v-max 4.5 --x100 0.9084 --r-int-ohm-cm2 "${MPM_S4_RINT:-50}" --d-s "${MPM_S4_DS:-3e-15}" --init-state "s4state_05n1.npz" --save-state "s4state_06n1.npz" --gpu \
    --out "step4_sched06n1_c2_rint${MPM_S4_RINT:-50}_ds${MPM_S4_DS:-3e-15}.npz" --viz-out "step4_sched06n1_viz_c2_rint${MPM_S4_RINT:-50}_ds${MPM_S4_DS:-3e-15}.json" \
    || echo "[run_mpm] 스케줄[6]cyc1 방전 2C FAILED — 다음 스텝 계속"
  fi
  echo "[run_mpm] STEP4 스케줄[7]cyc1 Rest 1min (I=0 완화 REST-LOCAL, 체인) $(date)"
  if [ ! -f "s4state_06n1.npz" ]; then echo "[run_mpm] 스케줄[7]cyc1 SKIP — 체인 끊김(s4state_06n1.npz 없음; step4_only.sh 로 재개)"; else
  python3 "$SCR/step4_dyn.py" --grid step4_grid.npz \
    --ocp-csv "$AP/ocp_nmc811_chen2020.csv" --params-json "$AP/params_nmc811_chen2020.json" \
    --rest --t-rest-min 1 --x100 0.9084 --d-s "${MPM_S4_DS:-3e-15}" --init-state "s4state_06n1.npz" --save-state "s4state_07n1.npz" \
    --out "step4_sched07n1_rest.npz" \
    || echo "[run_mpm] 스케줄[7]cyc1 Rest FAILED — 다음 스텝 계속"
  fi
  echo "[run_mpm] STEP4 스케줄[4] 충전 2C (CV@4.3V I<1C cyc2 · ★풀셀 축: R_int=${MPM_S4_RINT:-50} Ωcm² 직렬 · ★SC 단결정 단일 D_s=3e-15 m²/s (mono, σ_e AM_S=10 mS/cm)) $(date)"
  if [ ! -f "s4state_07n1.npz" ]; then echo "[run_mpm] 스케줄[4]cyc2 SKIP — 체인 끊김(s4state_07n1.npz 없음; step4_only.sh 로 재개)"; else
  python3 "$SCR/step4_dyn.py" --grid step4_grid.npz \
    --ocp-csv "$AP/ocp_nmc811_chen2020.csv" --params-json "$AP/params_nmc811_chen2020.json" \
    --c-rate 2 --charge --cv-hold --v-min 3 --v-max 4.3 --x100 0.9084 --i-cut-frac 1 --r-int-ohm-cm2 "${MPM_S4_RINT:-50}" --d-s "${MPM_S4_DS:-3e-15}" --init-state "s4state_07n1.npz" --save-state "s4state_04n2.npz" --gpu \
    --out "step4_sched04n2_chg_c2_rint${MPM_S4_RINT:-50}_ds${MPM_S4_DS:-3e-15}.npz" --viz-out "step4_sched04n2_viz_chg_c2_rint${MPM_S4_RINT:-50}_ds${MPM_S4_DS:-3e-15}.json" \
    || echo "[run_mpm] 스케줄[4]cyc2 충전 2C FAILED — 다음 스텝 계속"
  fi
  echo "[run_mpm] STEP4 스케줄[5]cyc2 Rest 1min (I=0 완화 REST-LOCAL, 체인) $(date)"
  if [ ! -f "s4state_04n2.npz" ]; then echo "[run_mpm] 스케줄[5]cyc2 SKIP — 체인 끊김(s4state_04n2.npz 없음; step4_only.sh 로 재개)"; else
  python3 "$SCR/step4_dyn.py" --grid step4_grid.npz \
    --ocp-csv "$AP/ocp_nmc811_chen2020.csv" --params-json "$AP/params_nmc811_chen2020.json" \
    --rest --t-rest-min 1 --x100 0.9084 --d-s "${MPM_S4_DS:-3e-15}" --init-state "s4state_04n2.npz" --save-state "s4state_05n2.npz" \
    --out "step4_sched05n2_rest.npz" \
    || echo "[run_mpm] 스케줄[5]cyc2 Rest FAILED — 다음 스텝 계속"
  fi
  echo "[run_mpm] STEP4 스케줄[6] 방전 2C (>=2.5V cyc2 · ★풀셀 축: R_int=${MPM_S4_RINT:-50} Ωcm² 직렬 · ★SC 단결정 단일 D_s=3e-15 m²/s (mono, σ_e AM_S=10 mS/cm)) $(date)"
  if [ ! -f "s4state_05n2.npz" ]; then echo "[run_mpm] 스케줄[6]cyc2 SKIP — 체인 끊김(s4state_05n2.npz 없음; step4_only.sh 로 재개)"; else
  python3 "$SCR/step4_dyn.py" --grid step4_grid.npz \
    --ocp-csv "$AP/ocp_nmc811_chen2020.csv" --params-json "$AP/params_nmc811_chen2020.json" \
    --c-rate 2 --v-min 2.5 --v-max 4.5 --x100 0.9084 --r-int-ohm-cm2 "${MPM_S4_RINT:-50}" --d-s "${MPM_S4_DS:-3e-15}" --init-state "s4state_05n2.npz" --save-state "s4state_06n2.npz" --gpu \
    --out "step4_sched06n2_c2_rint${MPM_S4_RINT:-50}_ds${MPM_S4_DS:-3e-15}.npz" --viz-out "step4_sched06n2_viz_c2_rint${MPM_S4_RINT:-50}_ds${MPM_S4_DS:-3e-15}.json" \
    || echo "[run_mpm] 스케줄[6]cyc2 방전 2C FAILED — 다음 스텝 계속"
  fi
  echo "[run_mpm] STEP4 스케줄[7]cyc2 Rest 1min (I=0 완화 REST-LOCAL, 체인) $(date)"
  if [ ! -f "s4state_06n2.npz" ]; then echo "[run_mpm] 스케줄[7]cyc2 SKIP — 체인 끊김(s4state_06n2.npz 없음; step4_only.sh 로 재개)"; else
  python3 "$SCR/step4_dyn.py" --grid step4_grid.npz \
    --ocp-csv "$AP/ocp_nmc811_chen2020.csv" --params-json "$AP/params_nmc811_chen2020.json" \
    --rest --t-rest-min 1 --x100 0.9084 --d-s "${MPM_S4_DS:-3e-15}" --init-state "s4state_06n2.npz" --save-state "s4state_07n2.npz" \
    --out "step4_sched07n2_rest.npz" \
    || echo "[run_mpm] 스케줄[7]cyc2 Rest FAILED — 다음 스텝 계속"
  fi
fi
ln -sfn "$RUN_DIR" "$KIT/latest_run"
touch "$RUN_DIR/mpm_done.marker"     # ★ 완료 마커 — '한 줄' 명령의 poll(until test -f latest_run/mpm_done.marker)용
echo "[run_mpm] DONE $(date) → 결과 폴더: $RUN_DIR  ($KIT/latest_run 심링크 = 여기)"
echo "          upload mpm_payload.json + mpm_metrics.json back to the case in the webapp"
echo "          (additive run이면 mpm_metrics.json의 step3.sigma_e_eff_S_cm = STEP3 σ_e — viewer 전류밀도 모드로 색칠)"
echo "          (step4 결과: step4_c*.npz/step4_chg_c*.npz = 곡선 시계열, step4_viz_*.json = 뷰어 st4 입력)"
echo "          (오래된 run_* 폴더는 디스크 차면 지워도 됨 — 산출물 회수 후)"
