"""Train/evaluate from raw data or a prepared CSV; export traceable Origin tables."""
from pathlib import Path
import argparse
import importlib.metadata
import json
import platform
import sys
import traceback
from datetime import datetime,timezone
import joblib
import numpy as np
import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font,PatternFill
from sklearn.metrics import roc_curve
from threadpoolctl import threadpool_limits
from config import VERSION,DataError,EvaluationError,config_dict,digest,load_config,write_json
from demo import make_demo
from extract_capacity import load_raw,validate_frame
from ridge_capacity import (classification_metrics,describe,fixed_baselines,nested_evaluate,
                            regression_metrics,select_model)

def versions():
    return {'python':platform.python_version(),**{p:importlib.metadata.version(p) for p in
            ['numpy','pandas','scikit-learn','scipy','joblib','openpyxl','threadpoolctl']}}

def outcome(y,pred):
    return np.where((y==1)&(pred==1),'TP',np.where((y==1)&(pred==0),'FN',np.where((y==0)&(pred==1),'FP','TN')))

def write_workbook(path,tables):
    """Plain tabular export generated by the Python application (no formulas)."""
    wb=Workbook()
    wb.remove(wb.active)
    for name,df in tables.items():
        sheet=wb.create_sheet(name)
        sheet.append(list(df.columns) if len(df.columns) else ['status'])
        if not len(df.columns):
            sheet.append(['not available; see run_summary.md'])
        for record in df.itertuples(index=False,name=None):
            cleaned=[]
            for v in record:
                if isinstance(v,(list,dict,tuple)):
                    v=json.dumps(v,ensure_ascii=False)
                elif hasattr(v,'item'):
                    v=v.item()
                if isinstance(v,float) and not np.isfinite(v):
                    v=None
                # Literal strings must not become spreadsheet formulas.
                if isinstance(v,str) and v.startswith(('=','+','-','@')):
                    v="'"+v
                cleaned.append(v)
            sheet.append(cleaned)
        sheet.freeze_panes='B2'
        sheet.auto_filter.ref=sheet.dimensions
        for cell in sheet[1]:
            cell.font=Font(bold=True,color='FFFFFF')
            cell.fill=PatternFill('solid',fgColor='25435B')
        for col in sheet.columns:
            letter=col[0].column_letter
            sheet.column_dimensions[letter].width=min(42,max(14,max(len(str(c.value or '')) for c in col[:30])+2))
            for cell in col[1:]:
                if isinstance(cell.value,float):
                    cell.number_format='0.000000'
    wb.save(path)

def run(frame,cfg,output,events,metadata):
    df,features=validate_frame(frame,cfg,events,training=True)
    df.to_csv(output/'input_features.csv',index=False,encoding='utf-8-sig')
    X=df[features]
    ids=df['cell_number'].to_numpy()
    groups=df[cfg.group_column].to_numpy() if cfg.outer_cv=='leave_one_group_out' else None
    cap=df['cap'].to_numpy()
    ybin=(cap<=cfg.threshold_ah).astype(int)
    oof=pd.DataFrame({'cell_number':ids,'measured_cap_Ah':cap,
                      'measured_cap_mAh_cm2':cap*1000/cfg.area_cm2,'true_label':ybin})
    if groups is not None:
        oof[cfg.group_column]=groups
    reg_rows=[]; clf_rows=[]; folds={}; unavailable={}; coefficients=[]; deployment={}
    (output/'models').mkdir()

    def save_final(name,x,y,cell_ids,kind,local_groups):
        model,trace=select_model(x,y,cell_ids,cfg,kind,local_groups)
        deployment[name]={'purpose':'Fit on all eligible data after OOF evaluation; not an independent performance estimate',**trace}
        bundle={'pipeline':model,'config':config_dict(cfg),'version':VERSION,'model_name':name,
                'input_features':list(x.columns),'training_cells':list(map(int,cell_ids)),
                'training_min':x.min().to_dict(),'training_max':x.max().to_dict(),
                'data_kind':metadata['data_kind']}
        joblib.dump(bundle,output/'models'/f'{name}.joblib')
        est=model.named_steps['model']
        if hasattr(est,'coef_'):
            for feature,value in zip(model.named_steps['select'].columns,np.asarray(est.coef_).ravel()):
                coefficients.append({'model':name,'feature':feature,'coefficient_standardized':float(value),
                                     'scope':'full-data final fit; not causal importance'})

    pred,trace=nested_evaluate(X,cap,ids,cfg,groups=groups)
    folds['capacity']=trace
    oof['pred_capacity_Ah']=pred
    oof['resid_capacity_Ah']=cap-pred
    metrics=regression_metrics(cap,pred)
    metrics.update(model='capacity_nested_selection',target='cap',RMSE_mAh_cm2=metrics['RMSE']*1000/cfg.area_cm2,
                   MAE_mAh_cm2=metrics['MAE']*1000/cfg.area_cm2)
    reg_rows.append(metrics)
    save_final('capacity',X,cap,ids,'regression',groups)
    for name,base_pred,m in fixed_baselines(X,cap,ids,cfg,groups):
        reg_rows.append({'model':'baseline_'+name,'target':'cap',**m})
        oof['baseline_'+name]=base_pred
    label=(pred<=cfg.threshold_ah).astype(int)
    score=cfg.threshold_ah-pred
    oof['score_capacity_threshold']=score
    oof['pred_capacity_threshold']=label
    oof['outcome_capacity_threshold']=outcome(ybin,label)
    clf_rows.append({'model':'capacity_threshold','score_unit':'Ah below capacity threshold',
                     **classification_metrics(ybin,label,score)})
    scores={'capacity_threshold':score}
    try:
        prob,trace=nested_evaluate(X,ybin,ids,cfg,kind='classification',groups=groups)
        folds['logistic']=trace
        label=(prob>=cfg.decision_threshold).astype(int)
        oof['score_logistic']=prob
        oof['pred_logistic']=label
        oof['outcome_logistic']=outcome(ybin,label)
        clf_rows.append({'model':'logistic_nested_selection','score_unit':'model probability; calibration unverified',
                         **classification_metrics(ybin,label,prob,probabilities=True)})
        scores['logistic']=prob
        save_final('logistic',X,ybin,ids,'classification',groups)
    except EvaluationError as exc:
        unavailable['logistic']=str(exc)
    if 'cc_frac' in df:
        mask=df['cc_frac'].notna().to_numpy()
        try:
            x=X.loc[mask]; y=df.loc[mask,'cc_frac'].to_numpy(); cells=ids[mask]
            local_groups=None if groups is None else groups[mask]
            prediction,trace=nested_evaluate(x,y,cells,cfg,groups=local_groups)
            folds['cc_fraction']=trace
            # Align by cell ID even when some CC fractions are absent.
            measured_map=dict(zip(cells,y)); pred_map=dict(zip(cells,prediction))
            oof['measured_cc_frac']=oof['cell_number'].map(measured_map)
            oof['pred_cc_frac']=oof['cell_number'].map(pred_map)
            oof['resid_cc_frac']=oof['measured_cc_frac']-oof['pred_cc_frac']
            reg_rows.append({'model':'ccfrac_nested_selection','target':'cc_frac',**regression_metrics(y,prediction)})
            save_final('cc_fraction',x,y,cells,'regression',local_groups)
        except EvaluationError as exc:
            unavailable['cc_fraction']=str(exc)
    else:
        unavailable['cc_fraction']='cc_frac column not provided'

    oof.to_csv(output/'oof_predictions.csv',index=False,encoding='utf-8-sig')
    pd.DataFrame(reg_rows).to_csv(output/'regression_metrics.csv',index=False,encoding='utf-8-sig')
    pd.DataFrame(clf_rows).to_csv(output/'classification_metrics.csv',index=False,encoding='utf-8-sig')
    write_json(output/'folds.json',folds)
    write_json(output/'deployment_fit.json',deployment)
    write_json(output/'metrics.json',{'regression':reg_rows,'classification':clf_rows,'unavailable':unavailable})
    roc_rows=[]
    if len(np.unique(ybin))==2:
        for name,s in scores.items():
            fpr,tpr,thresholds=roc_curve(ybin,s)
            roc_rows.extend({'model':name,'FPR':float(a),'TPR':float(b),'score_threshold':float(c)} for a,b,c in zip(fpr,tpr,thresholds))
    summary=[{'item':k,'value':v} for k,v in {'threshold_Ah':cfg.threshold_ah,'area_cm2':cfg.area_cm2,
        'design_capacity_Ah':cfg.design_capacity_ah,'n_samples':len(df),'n_defective':int(ybin.sum()),
        'n_normal':int(len(ybin)-ybin.sum()),'outer_cv':cfg.outer_cv,
        'logistic_decision_threshold':cfg.decision_threshold,'data_kind':metadata['data_kind'],
        'primary_selection':'feature set and regularization selected within outer training partitions',
        'external_validation_performed':False}.items()]
    summary.extend({'item':'unavailable_'+k,'value':v} for k,v in unavailable.items())
    cm=[]
    for r in clf_rows:
        cm.extend([{'model':r['model'],'actual':'defective','pred_defective':r['TP'],'pred_normal':r['FN']},
                   {'model':r['model'],'actual':'normal','pred_defective':r['FP'],'pred_normal':r['TN']}])
    grouped=oof[['cell_number','measured_cap_Ah','pred_capacity_Ah','outcome_capacity_threshold']].copy()
    grouped['measured_mAh_cm2']=grouped['measured_cap_Ah']*1000/cfg.area_cm2
    grouped['predicted_mAh_cm2']=grouped['pred_capacity_Ah']*1000/cfg.area_cm2
    tables={
        '01_reg_scatter':oof[[c for c in oof if c in ['cell_number','measured_cap_Ah','pred_capacity_Ah','measured_cc_frac','pred_cc_frac']]],
        '02_reg_metrics':pd.DataFrame(reg_rows),
        '03_reg_coefs':pd.DataFrame([c for c in coefficients if c['feature']!='ocv']),
        '03b_reg_coefs_ocv':pd.DataFrame([c for c in coefficients if c['feature']=='ocv']),
        '04_reg_residual':oof[[c for c in oof if c=='cell_number' or c.startswith(('measured_','pred_capacity_Ah','resid_'))]],
        '05_clf_roc':pd.DataFrame(roc_rows),
        '06_clf_metrics':pd.DataFrame(clf_rows),
        '07_clf_cellwise':oof[[c for c in oof if c in ['cell_number','measured_cap_Ah','true_label'] or c.startswith(('score_','pred_logistic','pred_capacity_threshold','outcome_'))]],
        '08_label_summary':pd.DataFrame(summary),
        '09_clf_scatter_grouped':grouped,
        '10_confusion_matrix':pd.DataFrame(cm),
    }
    write_workbook(output/'results_for_origin.xlsx',tables)
    text=[f'# 실행 결과 — {metadata["data_kind"]}', '',f'- 셀 수: {len(df)} (불량 {int(ybin.sum())}, 정상 {int(len(ybin)-ybin.sum())})',
          f'- 평가: {cfg.outer_cv}; 안쪽에서 대역·정규화 선택',
          '- 점수: 바깥 OOF 예측에서 계산. 최종 모델은 평가 후 전체 적격 자료에 적합.',
          '- 실제 신규 배치/셀에 대한 외부 검증은 수행되지 않았습니다.',
          '- Logistic의 출력은 보정이 확인된 실제 불량 확률이 아닙니다.',
          '- 기준선과 최종 선택 절차의 점수를 보고 다시 모델을 고르면 추가 독립 평가가 필요합니다.', '']
    if metadata['data_kind']=='synthetic_demo':
        text.append('**가상 데이터 실행 점수입니다. 실제 불량셀 성능으로 사용할 수 없습니다.**\n')
    if unavailable:
        text.append('## 계산하지 못한 항목\n')
        text.extend(f'- {name}: {reason}' for name,reason in unavailable.items())
    text.extend(['','## 확인 파일','', '- `oof_predictions.csv`: 셀별 실측·예측·잔차·판정',
                 '- `folds.json`: 바깥/안쪽 셀·그룹, 선택 설정, 표준화 평균',
                 '- `data_audit.json`, `config.json`, `run.json`: 입력 처리·설정·실행 출처',
                 '- `results_for_origin.xlsx`: Origin용 11개 표. 기존 버전과 열 구조는 다릅니다.',
                 '- `models/`: 전체 자료 적합 모델. `predict.py`로 새 CSV에 적용'])
    (output/'run_summary.md').write_text('\n'.join(text)+'\n',encoding='utf-8')
    return {'status':'partial' if unavailable else 'completed','n_cells':len(df),'unavailable':unavailable}

def main(argv=None):
    parser=argparse.ArgumentParser(description='Validated defective-cell ML with nested evaluation')
    source=parser.add_mutually_exclusive_group(required=True)
    source.add_argument('--demo',action='store_true',help='Artificial software-check data')
    source.add_argument('--features',help='Prepared CSV; cap is in Ah')
    source.add_argument('--cycle-dir',help='Raw cycler .txt directory; also requires --eis-dir')
    parser.add_argument('--eis-dir')
    parser.add_argument('--selection-manifest')
    parser.add_argument('--config')
    parser.add_argument('--synthetic-data',action='store_true',help='Explicitly mark a CSV/raw fixture run as artificial software-check data')
    parser.add_argument('--output',required=True,help='New output directory; existing directories are never overwritten')
    args=parser.parse_args(argv)
    if args.cycle_dir and not args.eis_dir:
        parser.error('--cycle-dir requires --eis-dir')
    if (args.eis_dir or args.selection_manifest) and not args.cycle_dir:
        parser.error('--eis-dir/--selection-manifest require --cycle-dir')
    try:
        cfg=load_config(args.config)
    except (DataError,ValueError,TypeError,OSError) as exc:
        parser.error(str(exc))
    output=Path(args.output).resolve()
    if output.exists():
        parser.error('Output directory already exists; choose a new directory')
    output.mkdir(parents=True)
    events=[]
    meta={'version':VERSION,'started_utc':datetime.now(timezone.utc).isoformat(),'status':'in_progress',
          'data_kind':'synthetic_demo' if args.demo or args.synthetic_data else 'user_data_protocol_not_independently_verified',
          'external_validation_performed':False,'versions':versions(),
          'config_path':str(Path(args.config).resolve()) if args.config else None,
          'code_sha256':{p.name:digest(p) for p in Path(__file__).resolve().parent.glob('*.py')}}
    write_json(output/'config.json',config_dict(cfg))
    write_json(output/'run.json',meta)
    try:
        if args.demo:
            frame=make_demo(cfg)
        elif args.features:
            frame=pd.read_csv(args.features)
            meta['input_csv']={'path':str(Path(args.features).resolve()),'sha256':digest(args.features)}
            events.append({'status':'prepared_csv','note':'Feature extraction/protocol must be verified independently'})
        else:
            if args.selection_manifest:
                meta['selection_manifest']={'path':str(Path(args.selection_manifest).resolve()),'sha256':digest(args.selection_manifest)}
            frame=load_raw(args.cycle_dir,args.eis_dir,cfg,events,args.selection_manifest)
        with threadpool_limits(limits=1):
            result=run(frame,cfg,output,events,meta)
        meta.update(result)
    except Exception as exc:
        meta.update(status='failed',error_type=type(exc).__name__,error=str(exc))
        (output/'error_traceback.txt').write_text(traceback.format_exc(),encoding='utf-8')
        print(f'Run failed: {exc}\nDetails: {output}',file=sys.stderr)
    finally:
        meta['finished_utc']=datetime.now(timezone.utc).isoformat()
        write_json(output/'data_audit.json',events)
        write_json(output/'run.json',meta)
    if meta['status']=='failed':
        return 2
    write_json(output/'artifact_hashes.json',{str(p.relative_to(output)):digest(p) for p in output.rglob('*') if p.is_file()})
    print(f'{meta["status"]}: {output} ({meta["n_cells"]} cells)')
    if meta.get('unavailable'):
        print('Some targets unavailable; see run_summary.md')
    return 0

if __name__=='__main__':
    raise SystemExit(main())
