#!/usr/bin/env bash
# MPM run for case 260421_215449_daf644 — generated by mpm_input_from_case.py
# SE (K-fixed): E_SE=1.53 GPa ν=0.49  (bulk K=25.5 GPa real-LPSC,
#   shear μ=0.5134 GPa = ×1.0 champion; from DEM E_eff 1.35 GPa),
#   press 0.3 GPa.  n_grid 256 → est ~89M points (budget 90M)
#   — kept tractable so the run FINISHES.  More SE resolution: regenerate with a higher
#   --max-points (heavier/slower) or edit --n-grid below.  If it OOMs, lower --n-grid / raise --gpu-mem.
set -uo pipefail
# ── 경로 자립: KIT = zip 푼 폴더(입력 csv), SCR = 레포 scripts/ (킷 폴더 또는 그 부모에서 탐색) ──
KIT="$(cd "$(dirname "$0")" && pwd)"
SCR=""; for c in "$KIT/scripts" "$KIT/../scripts"; do [ -d "$c" ] && SCR="$(cd "$c" && pwd)" && break; done
VENV_ON="${VIRTUAL_ENV:-}"; NO_VENV="${MPM_NO_VENV:-}"
# ── venv 자동탐지 (2026-07-29) ─────────────────────────────────────────────────────────
#   V100 실사고: run_mpm.sh 로는 되는데 같은 명령을 새 SSH 셸에서 직접 치면
#   ModuleNotFoundError: No module named 'numpy'.  레포 안 venv 를 새 세션이 자동으로
#   타지 않기 때문이다.  스크립트가 스스로 찾아 활성화한다.  이미 활성화돼 있거나
#   ($VIRTUAL_ENV) MPM_NO_VENV=1 이면 건드리지 않는다.
if [ -z "$VENV_ON" ] && [ -z "$NO_VENV" ]; then
  for _v in "$SCR/../venv" "$SCR/../.venv" "$KIT/../venv" "$HOME/Yonghoon-DEM-DFT/venv"; do
    if [ -f "$_v/bin/activate" ]; then . "$_v/bin/activate"; echo "[venv] activated: $_v"; break; fi
  done
fi
python3 -c "import numpy" >/dev/null 2>&1 || { echo "[venv] ABORT — 이 python3 에 numpy 가 없습니다: $(command -v python3)"; echo "        venv 를 못 찾았습니다 — source <repo>/venv/bin/activate 후 재실행하거나 MPM_NO_VENV=1 로 이 검사를 끄세요."; exit 1; }
if [ -z "$SCR" ]; then
  echo "[run_mpm] ABORT — scripts/ 를 못 찾음: 레포 루트(또는 scripts 심링크 있는 폴더)에 킷을 푸세요."
  exit 1
fi
# ── scripts 자동 최신화 (kit-gen↔runtime 버전 스큐 방지 = "--x100 unrecognized" 재발 차단; 끄기 MPM_NO_PULL=1) ──
if [ -z "${MPM_NO_PULL:-}" ] && [ -d "$SCR/../.git" ]; then
  echo "[run_mpm] git pull --ff-only (scripts 최신화)…"
  ( cd "$SCR/.." && git pull --ff-only ) || echo "  ⚠ git pull 스킵 — 기존 스크립트로 진행 (필요시 수동 pull)"
fi
# ── one GPU = one run: GPU 경합 방지 (산출물 충돌은 아래 RUN_DIR 격리가 원천 차단).  MPM_FORCE=1 로 무시 ──
if [ -z "${MPM_DETACHED:-}" ] && [ -z "${MPM_FORCE:-}" ] && pgrep -f 'mpm3d_compaction.py' >/dev/null 2>&1; then
  echo "[run_mpm] ABORT — an MPM run is already active (pgrep mpm3d_compaction).  one GPU = one run."
  echo "          wait for FINAL / 'kill <PID>' first, or 'MPM_FORCE=1 bash run_mpm.sh' to override."
  exit 1
fi
# ── self-detach: an SSH drop must NOT kill the run (the foreground run kept dying on disconnect). ──
# ── RUN_DIR = 런 전용 폴더: 모든 산출물이 여기에만 쓰임 → 다른 킷/이전 런과 절대 안 섞이고
#    (2026-07-17 SBE↔DBE 루트-덮어쓰기·mv-레이스 사고 재발 방지), 진행 중 외부 정리 작업의
#    영향도 없음.  완료 시 $KIT/latest_run 심링크가 이 폴더를 가리킴. ──
if [ -z "${MPM_DETACHED:-}" ]; then
  export MPM_DETACHED=1
  export RUN_DIR="$KIT/run_VGCF1_PTFE1_$(date +%Y%m%d_%H%M%S)_$$"
  mkdir -p "$RUN_DIR"
  log="$RUN_DIR/mpm_run.log"
  echo "→ detached — survives SSH drop.  run dir: $RUN_DIR"
  setsid nohup bash "$0" "$@" >"$log" 2>&1 </dev/null &
  echo "   PID $!     follow: tail -f $log     stop: kill $!"
  exit 0
fi
cd "$RUN_DIR"
# ===== actual run (detached; all output → this run dir only) =====
echo "[run_mpm] $(hostname) start $(date)  n_grid=256  est_pts~89M  dir=$RUN_DIR"
echo "[run_mpm] ────────────────────────────────────────────────────────────────"
echo "[run_mpm] ⚠ 구동압 스코프: 이 스크립트는 **제작압 300 MPa 형상**만 산출합니다."
echo "[run_mpm]   킷 이름의 _op90MPa 는 run_a1_anchors.sh (사이클 열화 앵커) 전용입니다."
echo "[run_mpm]   → STEP3 σ · STEP4 전기화학 · porosity/coverage 는 전부 제작압 형상 기준."
echo "[run_mpm]   → 구동압 형상이 필요하면: bash \$KIT/run_a1_anchors.sh (2단 제작→제하→구동)"
echo "[run_mpm]   근거: docs/temp_pressure_capability.md §3-3③ㄱ (제하 안 된 베드는 접촉면적·σ 과대)"
echo "[run_mpm] ────────────────────────────────────────────────────────────────"
# ── v3 열화-근접 옵션 (기본 안전 = 기존 convention 유지; §F1) ──────────────────────────────
#   MPM_FRACTURE=1        → 초기압밀 취성 crack-void (ASSUMED-FORM void frag0.15/pulv0.35; DEM=WHERE, MPM=형태)
#   MPM_PERIODIC_SIGMA=1  → STEP3 σ 측면 주기BC (bulk-RVE 정합; ⚠기존 corpus=절연벽 through-thickness → 전환 시 재run)
#   Joule 발열맵(#29) = 기본 ON (순수 진단 q∝|J|²/σ, σ/porosity 불변 → hot-spot '어디서 발열')
FRAC=()
if [ "${MPM_FRACTURE:-0}" = "1" ] && [ -f "$KIT/fracture_scaffold.csv" ]; then
  FRAC=(--fracture-scaffold "$KIT/fracture_scaffold.csv" --fracture-min-stage fragmentation)
  echo "[run_mpm] ★ MPM_FRACTURE=1 → 취성 crack-void 적용 (ASSUMED-FORM void; DEM 취성 위치 기반)"
fi
PSIG=(); [ "${MPM_PERIODIC_SIGMA:-0}" = "1" ] && { PSIG=(--periodic); echo "[run_mpm] ★ MPM_PERIODIC_SIGMA=1 → STEP3 σ 주기BC (bulk-RVE)"; }
# 1) plastic compaction of the REAL SE around the fixed AM scaffold (periodic x,y RVE = DEM 'boundary p p f')
python3 "$SCR/mpm3d_compaction.py" \
  --am-scaffold "$KIT/am_scaffold.csv" --se-dump "$KIT/se_scaffold.csv" --periodic \
  --lateral-box 0.05 --n-grid 256 --arch cuda --gpu-mem 28 --protocol hold --frames 150 \
  --e-se 1.53 --nu-se 0.49 --target-gpa 0.3 \
  --save-se se_dump.npy --save-dg se_dump_dg.npy --save-eps se_dump_eps.npy --save-metrics mpm_metrics.json \
  --add-recipe "VGCF:PTFE=1:1" --add-l-cv 0.4 --mixing thinky --coh-ptfe 0.10 --binder-opt-wt 1.5 --fibre-buckle --fibre-align 0.666 --dilate-z 1.0214 --save-phase phase.npy --save-fibre fibre.npy --save-fibre-dia fibre_dia.npy "${FRAC[@]}" \
  || { echo "[run_mpm] STEP 1 (compaction) FAILED — see the trace above.  NOT running the payload: it would"; \
        echo "          rebuild mpm_payload.json from the STALE se_dump.npy of a PREVIOUS run and report a"; \
        echo "          leftover porosity as if it were this run.  Fix the error and re-run."; exit 1; }
# 2) webapp payload (AM spheres + SE surface + seed/compacted + raw metrics)
#    + STEP3 σ_e 저항망 (전도상 voxel Kirchhoff, 풀해상도 — metrics.step3.sigma_e_eff + 입자별 je;
#      상대비교용 σ표는 metrics에 기록됨.  끄기: --no-step3)
# ★ 운전 온도 60 °C (webapp &tempc=) — σ_ion(SE) 은 Kraft-2017 σ·T Arrhenius,
#   i0 는 kim2025 R_ct(T) 앵커로 스케일 (STEP4 에 --temp-k 333.15 --i0-temp-scale 을 **한 쌍으로** 주입 — 한쪽만 주면 부호역전/거짓라벨).
#   D_s/OCP dU/dT/σ_e/κ/SE-경도는 앵커 없어 25 °C 상수 → 전-물리 온도 스윕 아님 (docs/temp_pressure_capability.md §3).  Eₐ 는 밴드 0.29/0.41/0.46 eV 를 쓸어 보고할 것.
python3 "$SCR/mpm_webapp_payload.py" --temp-c 60 \
  --se se_dump.npy --scaffold "$KIT/am_scaffold.csv" --se-dump "$KIT/se_scaffold.csv" \
  --n-vox 192 --tri-step 4 --smooth 1.5 --target-porosity 0.1595 --eps se_dump_eps.npy --dilate-z 1.0214 \
  --void-max 180000 --step3-vox 0.4 --field-max-points 90000 --step3-gpu --joule-heat "${PSIG[@]}" --metrics-json mpm_metrics.json --case 260421_215449_daf644 --phase phase.npy --fibre fibre.npy --fibre-dia fibre_dia.npy --collector-rint 150 --collector-name SUS_bare_estimated --collector-scenario sus --save-step4-grid step4_grid.npz --out mpm_payload.json \
  || { echo "[run_mpm] STEP 2 (payload) FAILED — 압밀(se_dump.npy)은 무사하니 원인 수정 후 payload만 재실행:"; \
        echo "          cd $RUN_DIR && bash $KIT/step4_only.sh 는 STEP4용이고, payload는:"; \
        echo "          sed -n '/mpm_webapp_payload/,/--out mpm_payload.json/p' $KIT/run_mpm.sh > payload_only.sh && bash payload_only.sh"; \
        echo "          (흔한 원인: pip 모듈 누락 — python3 -m pip install scikit-image scipy)"; exit 1; }
ln -sfn "$RUN_DIR" "$KIT/latest_run"
touch "$RUN_DIR/mpm_done.marker"     # ★ 완료 마커 — '한 줄' 명령의 poll(until test -f latest_run/mpm_done.marker)용
echo "[run_mpm] DONE $(date) → 결과 폴더: $RUN_DIR  ($KIT/latest_run 심링크 = 여기)"
echo "          upload mpm_payload.json + mpm_metrics.json back to the case in the webapp"
echo "          (additive run이면 mpm_metrics.json의 step3.sigma_e_eff_S_cm = STEP3 σ_e — viewer 전류밀도 모드로 색칠)"
echo "          (step4 결과: step4_c*.npz/step4_chg_c*.npz = 곡선 시계열, step4_viz_*.json = 뷰어 st4 입력)"
echo "          (오래된 run_* 폴더는 디스크 차면 지워도 됨 — 산출물 회수 후)"
