#!/usr/bin/env python3
"""Build QE band-structure NSCF input + bands.x post-processing input.

Reads V0_relax.in (template) + V0_relax.out (final coords) and writes:
  - nscf_bands.in     : pw.x calculation='bands' along auto-detected BZ path
  - bands_post.in     : bands.x input to extract eigenvalues along path
  - run_bands.sh      : driver script (mirrors run_V0.sh env)

K-path is auto-generated by ASE's BandPath (or seekpath if available).
Re-uses existing wfc in tmp_V0/ (from V0_relax SCF), so no extra SCF needed.

Usage:
    python3 build_bands_inputs.py \\
        --v0_in  /home/ubuntu/work/runs/modelC_v3/V0_relax.in \\
        --v0_out /home/ubuntu/work/runs/modelC_v3/V0_relax.out \\
        --out_dir /home/ubuntu/work/runs/modelC_v3 \\
        --n_kpoints 30 \\
        --special_path "auto"
"""
import argparse
import re
import shutil
from pathlib import Path


def parse_v0_relax_input(v0_in_path):
    """Extract original CONTROL/SYSTEM/ELECTRONS/ATOMIC_SPECIES/CELL/POSITIONS
    text from V0_relax.in. Returns dict of sections.
    """
    text = v0_in_path.read_text()
    # Split into namelists vs cards
    nls = {}
    cards = {}
    cur = None
    cur_text = []
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("&"):
            name = s[1:].split()[0].upper()
            cur = ("nl", name)
            cur_text = [line]
        elif s == "/" and cur and cur[0] == "nl":
            cur_text.append(line)
            nls[cur[1]] = "\n".join(cur_text)
            cur = None; cur_text = []
        elif s.startswith(("ATOMIC_SPECIES", "K_POINTS", "CELL_PARAMETERS",
                            "ATOMIC_POSITIONS", "OCCUPATIONS", "HUBBARD")):
            if cur and cur[0] == "card":
                cards[cur[1]] = "\n".join(cur_text)
            cur = ("card", s.split()[0])
            cur_text = [line]
        elif cur:
            cur_text.append(line)
    if cur and cur[0] == "card":
        cards[cur[1]] = "\n".join(cur_text)
    return nls, cards


def parse_final_coords_from_out(v0_out_path):
    """Extract final ATOMIC_POSITIONS (+ optional CELL_PARAMETERS) from QE
    relax output (after 'End of BFGS Geometry Optimization' or last set).
    Returns (cell_block_str_or_None, positions_block_str).
    """
    text = v0_out_path.read_text()
    # Find LAST CELL_PARAMETERS occurrence (vc-relax) — may be absent for fixed cell
    cell_match = list(re.finditer(
        r"CELL_PARAMETERS\s*\([^)]+\)\n((?:\s*[-+\d.E\s]+\n){3})", text))
    cell_block = None
    if cell_match:
        m = cell_match[-1]
        cell_block = f"CELL_PARAMETERS angstrom\n" \
                     if "angstrom" in m.group(0) else \
                     f"CELL_PARAMETERS alat\n"
        cell_block += m.group(1)
    # Find LAST ATOMIC_POSITIONS
    pos_match = list(re.finditer(
        r"ATOMIC_POSITIONS\s*\(([^)]+)\)\n((?:[A-Za-z]\w*\s+[-+\d.E\s]+\n)+)",
        text))
    if not pos_match:
        raise SystemExit(f"{v0_out_path}: no ATOMIC_POSITIONS in output")
    m = pos_match[-1]
    units = m.group(1).strip()
    pos_block = f"ATOMIC_POSITIONS ({units})\n{m.group(2)}"
    return cell_block, pos_block


def _parse_cell_from_in(v0_in_path):
    """Parse initial CELL_PARAMETERS from V0_relax.in (for fixed-cell relax)."""
    txt = v0_in_path.read_text()
    m = re.search(
        r"CELL_PARAMETERS\s*(?:\(?\s*(angstrom|bohr|alat)\s*\)?)?\s*\n"
        r"((?:[-+\d.E\s]+\n){3})", txt, re.IGNORECASE)
    if not m:
        return None, None
    unit = (m.group(1) or "alat").lower()
    rows = []
    for line in m.group(2).strip().splitlines()[:3]:
        rows.append([float(x) for x in line.split()[:3]])
    return rows, unit


def _parse_alat_bohr(v0_in_path):
    """Parse celldm(1) (alat in bohr) from V0_relax.in &SYSTEM."""
    txt = v0_in_path.read_text()
    m = re.search(r"celldm\(1\)\s*=\s*([-+\d.E]+)", txt)
    return float(m.group(1)) if m else None


def build_k_path(v0_in_path, v0_out_path, n_kpoints, pos_block):
    """Build BandPath. Fallback: construct ase.Atoms from raw cell + positions."""
    from ase import Atoms
    from ase.io import read
    from pathlib import Path
    import numpy as np

    # Try ASE Espresso parser first
    atoms = None
    try:
        from ase.io.espresso import read_espresso_out
        atoms = list(read_espresso_out(str(v0_out_path), index=slice(-1, None)))[-1]
        print(f"  cell from ASE espresso parser")
    except Exception as e:
        print(f"  ASE espresso parser failed ({type(e).__name__}); fallback to raw parse")

    if atoms is None:
        # Fallback: parse cell from V0_relax.in, positions from V0_relax.out
        BOHR_TO_A = 0.5291772108
        cell_rows, unit = _parse_cell_from_in(v0_in_path)
        if cell_rows is None:
            raise SystemExit(
                f"Could not parse CELL_PARAMETERS from {v0_in_path}; "
                "edit script to specify cell manually.")
        cell = np.array(cell_rows)
        if unit == "bohr":
            cell *= BOHR_TO_A
        elif unit == "alat":
            alat_bohr = _parse_alat_bohr(v0_in_path)
            if alat_bohr is None:
                raise SystemExit("CELL_PARAMETERS alat but no celldm(1) in &SYSTEM")
            cell *= (alat_bohr * BOHR_TO_A)
        # angstrom: keep as-is

        # Parse positions from already-extracted pos_block
        # pos_block format: "ATOMIC_POSITIONS (units)\n<element> x y z\n..."
        lines = pos_block.strip().splitlines()
        units_pos = re.search(r"\(([^)]+)\)", lines[0]).group(1).strip().lower()
        syms = []; coords = []
        for ln in lines[1:]:
            parts = ln.split()
            if len(parts) < 4:
                continue
            syms.append(parts[0])
            coords.append([float(x) for x in parts[1:4]])
        coords = np.array(coords)
        if units_pos == "crystal":
            atoms = Atoms(symbols=syms, scaled_positions=coords, cell=cell, pbc=True)
        elif units_pos in ("bohr",):
            atoms = Atoms(symbols=syms, positions=coords * BOHR_TO_A, cell=cell, pbc=True)
        elif units_pos == "alat":
            alat_bohr = _parse_alat_bohr(v0_in_path)
            atoms = Atoms(symbols=syms, positions=coords * alat_bohr * BOHR_TO_A,
                          cell=cell, pbc=True)
        else:  # angstrom
            atoms = Atoms(symbols=syms, positions=coords, cell=cell, pbc=True)
        print(f"  cell + positions parsed manually (units pos={units_pos})")
        print(f"  cell:\n{atoms.cell.array}")
        print(f"  n_atoms = {len(atoms)}")

    # Auto BandPath
    bp = atoms.cell.bandpath(npoints=n_kpoints * 5)
    print(f"  Auto k-path: {bp.path}  ({len(bp.kpts)} k-points)")
    return bp, atoms


def write_kpts_crystal_b(bp, n_per_seg=30):
    """Format the k-path as QE K_POINTS crystal_b cards (one line per special pt)."""
    # crystal_b: each line is "kx ky kz n_divisions_to_next"
    # Parse path string like "GXMGRX|MR" into segments
    path = bp.path
    segments = path.split(",") if "," in path else path.split("|")
    # Actually QE crystal_b expects special-points + segments. Simpler:
    # list special pts + n_pts to next (0 = endpoint)
    special = bp.special_points
    if not special:
        raise SystemExit("BandPath has no special points; specify --special_path manually")
    lines = []
    pts = []
    # Walk through path char by char
    i = 0
    chunks = []
    while i < len(path):
        c = path[i]
        if c in ",|":
            i += 1; continue
        # match potential 2-char point name (e.g., G1, X2)
        if i + 1 < len(path) and path[i+1] not in ",|" and path[i+1] in "₀₁₂345":
            name = path[i:i+2]; i += 2
        else:
            name = c; i += 1
        chunks.append((name, c in [path[-1]] or i >= len(path) or path[i] in ",|"))
    # Re-pack: just list special points in order with n_per_seg, last gets 1
    seq = []
    cur = []
    for name, _ in chunks:
        cur.append(name)
    # Output
    lines = []
    n_pts = len(cur)
    for j, name in enumerate(cur):
        if name not in special:
            print(f"  [warn] {name} not in special_points; skipping")
            continue
        kx, ky, kz = special[name]
        is_last = (j == len(cur) - 1)
        n_div = 0 if is_last else n_per_seg
        lines.append(f"  {kx:10.6f} {ky:10.6f} {kz:10.6f}  {n_div}   ! {name}")
    return "K_POINTS crystal_b\n" + f"  {len(lines)}\n" + "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--v0_in", required=True)
    ap.add_argument("--v0_out", required=True)
    ap.add_argument("--out_dir", required=True)
    ap.add_argument("--n_kpoints", type=int, default=30,
                    help="k-points per segment")
    ap.add_argument("--prefix", default="V0",
                    help="QE prefix (must match V0_relax)")
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    v0_in = Path(args.v0_in); v0_out = Path(args.v0_out)
    assert v0_in.exists() and v0_out.exists()

    nls, cards = parse_v0_relax_input(v0_in)
    cell_block, pos_block = parse_final_coords_from_out(v0_out)
    print(f"Final coords parsed from {v0_out.name}")

    # Build k-path (with fallback for ASE espresso parse failure)
    bp, atoms = build_k_path(v0_in, v0_out, args.n_kpoints, pos_block)
    kpoints_card = write_kpts_crystal_b(bp, n_per_seg=args.n_kpoints)

    # Build CONTROL for bands calc
    # Modify calculation='bands', verbosity='high', tprnfor/tstress can be false
    control = nls["CONTROL"]
    control = re.sub(r"calculation\s*=\s*'[^']*'",
                     "calculation = 'bands'", control)
    if "verbosity" not in control:
        control = control.replace("/", "  verbosity = 'high'\n/", 1)
    # Also ensure restart_mode='from_scratch' (NSCF needs fresh wf-read)
    if "restart_mode" not in control:
        control = control.replace("/", "  restart_mode = 'from_scratch'\n/", 1)

    # SYSTEM: add nbnd buffer (~1.3× occupied) — auto-estimate is fine via QE,
    # but explicitly set ~50% above default for clean dispersion plotting.
    system = nls["SYSTEM"]
    # leave SYSTEM as-is; bands inherits nbnd from SCF wfc

    # Assemble nscf_bands.in
    bands_input = (
        control + "\n" +
        system + "\n" +
        nls.get("ELECTRONS", "&ELECTRONS\n  conv_thr = 1.0d-8\n/") + "\n" +
        cards.get("ATOMIC_SPECIES", "") + "\n" +
        kpoints_card + "\n" +
        (cell_block + "\n" if cell_block else "") +
        pos_block + "\n"
    )
    out_dir.joinpath("nscf_bands.in").write_text(bands_input)
    print(f"  → {out_dir / 'nscf_bands.in'}")

    # bands_post.in for bands.x
    bands_post = f"""&BANDS
  prefix = '{args.prefix}'
  outdir = './tmp_{args.prefix}/'
  filband = 'bands.dat'
  lsym = .true.
/
"""
    out_dir.joinpath("bands_post.in").write_text(bands_post)
    print(f"  → {out_dir / 'bands_post.in'}")

    # Driver script
    run_sh = f"""#!/bin/bash
# Band-structure post-processing for {args.prefix}.
# Re-uses wavefunctions from tmp_{args.prefix}/ (V0_relax SCF output).
set -e
cd $(dirname $(realpath $0))
export OMP_NUM_THREADS=8

NSCF=nscf_bands.in
NSCF_OUT=nscf_bands.out
BANDS_IN=bands_post.in
BANDS_OUT=bands_post.out

echo "[$(date)] modelC_v3 band-structure NSCF START"
nvidia-smi --query-gpu=index,utilization.gpu,memory.used --format=csv,noheader

T0=$(date +%s)
mpirun --bind-to none -np 1 pw.x -inp $NSCF > $NSCF_OUT 2>&1 || \\
    echo "[$(date +%H:%M:%S)] WARN: pw.x nonzero exit"
DT=$(( $(date +%s) - T0 ))
echo "[$(date +%H:%M:%S)] NSCF done in ${{DT}}s"

if ! grep -q "JOB DONE" $NSCF_OUT; then
    echo "ERROR: bands NSCF did not converge — check $NSCF_OUT"
    tail -20 $NSCF_OUT
    exit 1
fi

echo "[$(date +%H:%M:%S)] bands.x post-processing"
mpirun --bind-to none -np 1 bands.x -inp $BANDS_IN > $BANDS_OUT 2>&1 || true
ls -la bands.dat bands.dat.gnu 2>/dev/null || echo "  (bands.dat not yet)"

echo "[$(date)] DONE"
"""
    sh_path = out_dir / "run_bands.sh"
    sh_path.write_text(run_sh)
    sh_path.chmod(0o755)
    print(f"  → {sh_path} (executable)")


if __name__ == "__main__":
    main()
