#!/usr/bin/env python3
"""4-panel pCOHP / ICOHP plot from LOBSTER output, matching paper Fig style.

Reads COHPCAR.lobster + ICOHPLIST.lobster from a LOBSTER run on modelC_v3
V0 SCF output. Produces a 4-panel horizontal figure (P-S | S-S | Li-S | Li-Cl)
with:
  - vertical layout: E - E_F (eV) on y, -pCOHP on x
  - bonding region (+x, right side) shaded
  - antibonding region (-x, left side) shaded
  - E_F dashed horizontal line at 0
  - ICOHP value in a rounded box at bottom of each panel
  - "Antibonding" / "Bonding" italic labels

Usage:
    python3 plot_lobster_4panel.py \\
        --lobster_dir /home/ubuntu/work/runs/modelC_v3 \\
        --out_png    /home/ubuntu/work/runs/modelC_v3/V0_COHP_4panel.png
"""
import argparse
import re
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch


PANEL_CONFIG = [
    {"label": "P–S",   "color": "#3F7BB6", "match_keys": ["P", "S"],   "exclude": ["Li"]},
    {"label": "S–S",   "color": "#C44536", "match_keys": ["S", "S"],   "exclude": ["P", "Li", "Cl"]},
    {"label": "Li–S",  "color": "#3E8E41", "match_keys": ["Li", "S"],  "exclude": []},
    {"label": "Li–Cl", "color": "#E89C2B", "match_keys": ["Li", "Cl"], "exclude": []},
]


def parse_cohpcar(path: Path):
    """Parse LOBSTER 5.x COHPCAR.lobster.

    Format:
        Line 1: 'ESCALE ; pCOHP file generated by LOBSTER ...'
        Line 2: n_bonds  n_spin  n_energies  E_min  E_max  ?  (whitespace)
        Line 3: 'Average'   (header for total/avg column in data block)
        Lines 4 .. (3 + n_bonds): bond defs 'No.N:Atom1X->Atom2Y(distance)'
        Then n_energies rows of:
            E  total_pCOHP  total_iCOHP  b1_pCOHP  b1_iCOHP  b2_pCOHP  b2_iCOHP ...

    Returns:
        E : 1-D ndarray (E - E_F), eV
        bonds : list[dict], one per bond:
            { 'id': int, 'a': elem1, 'b': elem2, 'distance': float, 'pcohp': ndarray }
        Note: we flip sign so 'pcohp' = -pCOHP (bonding > 0, antibonding < 0).
    """
    lines = path.read_text().splitlines()
    # Line 1 header — skip.
    # Line 2 meta
    meta = lines[1].split()
    n_bonds = int(meta[0])
    n_energies = int(meta[2])

    bonds_meta = []  # list of {id, a, b, distance}
    iline = 2
    # 'Average' line then n_bonds bond defs. Some LOBSTER builds skip 'Average'.
    if lines[iline].strip().lower().startswith("average"):
        iline += 1
    bond_re = re.compile(
        r"No\.(\d+):\s*([A-Za-z]+)\d+->\s*([A-Za-z]+)\d+\(([\d.]+)\)")
    while len(bonds_meta) < n_bonds and iline < len(lines):
        m = bond_re.match(lines[iline].strip())
        if m:
            bonds_meta.append({
                "id": int(m.group(1)),
                "a": m.group(2),
                "b": m.group(3),
                "distance": float(m.group(4)),
            })
            iline += 1
        else:
            iline += 1  # skip any unexpected line (rare)
    n_bonds_actual = len(bonds_meta)

    # Parse energy block. Column layout per row:
    #   col 0 = E - E_F
    #   col 1 = total pCOHP    col 2 = total ICOHP
    #   col 3 = b1 pCOHP        col 4 = b1 ICOHP
    #   col 5 = b2 pCOHP        col 6 = b2 ICOHP
    #   ...
    E = []
    cohp = [[] for _ in range(n_bonds_actual)]
    while iline < len(lines) and len(E) < n_energies:
        parts = lines[iline].split()
        iline += 1
        if len(parts) < 3 + 2 * n_bonds_actual:
            continue
        try:
            E.append(float(parts[0]))
            for b in range(n_bonds_actual):
                cohp[b].append(float(parts[3 + 2 * b]))
        except ValueError:
            continue
    E = np.array(E)
    for b in range(n_bonds_actual):
        # Flip sign so bonding > 0 on plot x-axis.
        bonds_meta[b]["pcohp"] = -np.array(cohp[b])
    return E, bonds_meta


def parse_icohplist(path: Path):
    """Parse ICOHPLIST.lobster: returns {bond_label: ICOHP value (eV)}."""
    icohp_per_bond_idx = {}
    for line in path.read_text().splitlines():
        s = line.strip()
        if not s or s.startswith("#") or s.startswith("COHP") or s.startswith("LABEL"):
            continue
        parts = s.split()
        if len(parts) >= 7:
            try:
                idx = int(parts[0])
                a1 = re.sub(r"\d", "", parts[1])
                a2 = re.sub(r"\d", "", parts[2])
                icohp = float(parts[7]) if len(parts) > 7 else float(parts[-1])
                key = f"{a1}-{a2}"
                icohp_per_bond_idx.setdefault(key, []).append(icohp)
            except (ValueError, IndexError):
                continue
    return {k: float(np.mean(v)) for k, v in icohp_per_bond_idx.items()}


def aggregate_bond_pair(E, bonds_meta, icohp_data, match_keys, exclude=None):
    """Sum -pCOHP across all bonds matching the requested element pair.

    bonds_meta: list of {id, a, b, distance, pcohp}.
    icohp_data: {f"{elem1}-{elem2}": mean_ICOHP_eV} from ICOHPLIST.
    Returns (cohp_summed_array, icohp_per_bond_avg, n_matched).
    """
    exclude = set(exclude or [])
    target = set(match_keys)
    matched = [bm for bm in bonds_meta
               if {bm["a"], bm["b"]} == target
               and not (exclude & {bm["a"], bm["b"]})]
    if not matched:
        return np.zeros_like(E), 0.0, 0
    summed = np.sum([bm["pcohp"] for bm in matched], axis=0)
    a, b = match_keys
    icohp_per_bond_avg = icohp_data.get(
        f"{a}-{b}", icohp_data.get(f"{b}-{a}", 0.0))
    return summed, icohp_per_bond_avg, len(matched)


def plot_panel(ax, E, cohp, color, label, icohp_value, fermi_ref=0.0,
                xlim=None, ylim=(-12, 6)):
    """Draw one COHP panel — paper style."""
    # shade left half (antibonding) and right half (bonding) lightly
    if xlim is None:
        xmax = max(abs(cohp).max() * 1.15, 1.0)
        xlim = (-xmax, xmax)

    # filled curve on right (bonding region of -pCOHP)
    bonding_x = np.where(cohp > 0, cohp, 0)
    antibond_x = np.where(cohp < 0, cohp, 0)
    ax.fill_betweenx(E - fermi_ref, 0, bonding_x, color=color, alpha=0.55, lw=0)
    ax.fill_betweenx(E - fermi_ref, 0, antibond_x, color=color, alpha=0.55, lw=0)
    # outline
    ax.plot(cohp, E - fermi_ref, '-', color=color, lw=1.0)

    # zero vertical line
    ax.axvline(0, color='k', lw=0.7)
    # Fermi horizontal
    ax.axhline(0, color='#666', linestyle='--', lw=0.8)

    ax.set_xlim(xlim)
    ax.set_ylim(ylim)
    ax.set_xlabel(r"$-$pCOHP", fontsize=12)
    ax.tick_params(labelsize=10)

    # Antibonding (top-left) and Bonding (bottom-right) text
    ax.text(xlim[0] + (xlim[1] - xlim[0]) * 0.08,
            ylim[1] - (ylim[1] - ylim[0]) * 0.10,
            "Antibonding", fontsize=10, fontstyle='italic', color='#999', ha='left')
    ax.text(xlim[1] - (xlim[1] - xlim[0]) * 0.08,
            ylim[0] + (ylim[1] - ylim[0]) * 0.42,
            "Bonding", fontsize=10, fontstyle='italic', color='#999', ha='right')
    # E_F label
    ax.text(xlim[1] - (xlim[1] - xlim[0]) * 0.05, 0.1,
            r"$E_F$", fontsize=10, color='#666', ha='right', va='bottom')

    # Legend (label in top-right)
    leg_text = label
    ax.text(xlim[1] - (xlim[1] - xlim[0]) * 0.05, ylim[1] - (ylim[1] - ylim[0]) * 0.04,
            leg_text, fontsize=12, fontweight='bold',
            ha='right', va='top', bbox=dict(facecolor=color, alpha=0.18,
                                              edgecolor='none', boxstyle='round,pad=0.3'))

    # ICOHP box at bottom
    icohp_str = f"ICOHP = {icohp_value:.3f} eV"
    ax.text(0, ylim[0] + (ylim[1] - ylim[0]) * 0.04, icohp_str,
            ha='center', va='bottom', fontsize=11, fontweight='bold',
            bbox=dict(boxstyle="round,pad=0.4", facecolor='white',
                       edgecolor='#666', lw=0.8))

    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--lobster_dir", required=True,
                    help="dir containing COHPCAR.lobster + ICOHPLIST.lobster")
    ap.add_argument("--out_png", required=True)
    ap.add_argument("--ylim", type=float, nargs=2, default=[-12, 6])
    args = ap.parse_args()

    work = Path(args.lobster_dir)
    cohp_path = work / "COHPCAR.lobster"
    icohp_path = work / "ICOHPLIST.lobster"
    if not cohp_path.exists() or not icohp_path.exists():
        raise SystemExit(f"missing LOBSTER files in {work}")

    E, bonds_meta = parse_cohpcar(cohp_path)
    icohp = parse_icohplist(icohp_path)
    print(f"Parsed {len(bonds_meta)} bond entries × {len(E)} energy points")
    print(f"ICOHP averages per element pair:")
    for k, v in sorted(icohp.items()):
        print(f"  {k}: {v:.3f} eV")

    fig, axes = plt.subplots(1, 4, figsize=(16, 6), sharey=True)
    for ax, cfg in zip(axes, PANEL_CONFIG):
        cohp_sum, icohp_per_bond, nb = aggregate_bond_pair(
            E, bonds_meta, icohp, cfg["match_keys"], cfg["exclude"])
        print(f"  panel {cfg['label']}: matched {nb} bonds, "
              f"ICOHP/bond = {icohp_per_bond:.3f} eV")
        plot_panel(ax, E, cohp_sum, cfg["color"], cfg["label"],
                    icohp_per_bond, ylim=tuple(args.ylim))
        if nb == 0:
            ax.text(0.5, 0.5, f"no {cfg['label']} bonds", transform=ax.transAxes,
                    ha='center', color='#999', fontsize=12)
    axes[0].set_ylabel(r"$E - E_F$  (eV)", fontsize=12)

    # subplot letter labels
    for letter, ax in zip("abcd", axes):
        ax.text(-0.10, 1.02, letter, transform=ax.transAxes,
                fontsize=16, fontweight='bold', ha='right', va='bottom')

    plt.tight_layout()
    plt.savefig(args.out_png, dpi=300, bbox_inches='tight', facecolor='white')
    print(f"\n→ {args.out_png}")


if __name__ == "__main__":
    main()
