#!/usr/bin/env python3
"""4-panel pCOHP / ICOHP plot from LOBSTER output, matching paper Fig style.

Reads COHPCAR.lobster + ICOHPLIST.lobster from a LOBSTER run on modelC_v3
V0 SCF output. Produces a 4-panel horizontal figure (P-S | S-S | Li-S | Li-Cl)
with:
  - vertical layout: E - E_F (eV) on y, -pCOHP on x
  - bonding region (+x, right side) shaded
  - antibonding region (-x, left side) shaded
  - E_F dashed horizontal line at 0
  - ICOHP value in a rounded box at bottom of each panel
  - "Antibonding" / "Bonding" italic labels

Usage:
    python3 plot_lobster_4panel.py \\
        --lobster_dir /home/ubuntu/work/runs/modelC_v3 \\
        --out_png    /home/ubuntu/work/runs/modelC_v3/V0_COHP_4panel.png
"""
import argparse
import re
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch


PANEL_CONFIG = [
    {"label": "P–S",   "color": "#3F7BB6", "match_keys": ["P", "S"],   "exclude": ["Li"], "dmax": 2.6},
    {"label": "S–S",   "color": "#C44536", "match_keys": ["S", "S"],   "exclude": ["P", "Li", "Cl"]},
    {"label": "Li–S",  "color": "#3E8E41", "match_keys": ["Li", "S"],  "exclude": []},
    {"label": "Li–Cl", "color": "#E89C2B", "match_keys": ["Li", "Cl"], "exclude": []},
]

# nd (Nd2O3-doped) preset: swap S–S/Li–Cl for the O actor (P–O) + Nd ionic (Nd–S).
# P–S kept (dmax 2.6 = tetrahedral only, matches bar -5.98) for host overlay vs modelc.
NDPANEL_CONFIG = [
    {"label": "P–S",  "color": "#3F7BB6", "match_keys": ["P", "S"],  "exclude": ["Li"], "dmax": 2.6},
    {"label": "P–O",  "color": "#C44536", "match_keys": ["P", "O"],  "exclude": []},
    {"label": "Li–S", "color": "#3E8E41", "match_keys": ["Li", "S"], "exclude": []},
    {"label": "Nd–S", "color": "#7D5BA6", "match_keys": ["Nd", "S"], "exclude": []},
]
PRESETS = {"modelc": PANEL_CONFIG, "nd": NDPANEL_CONFIG}
_PAIR_COLORS = ["#3F7BB6", "#C44536", "#3E8E41", "#E89C2B", "#7D5BA6", "#2BB0A8"]


def build_panels(panels_arg):
    """--panels 'P-S,P-O,Li-S,Nd-S' -> list of panel configs (cycled colors)."""
    out = []
    for i, p in enumerate(panels_arg.split(",")):
        a, _, b = p.strip().partition("-")
        out.append({"label": f"{a}–{b}", "color": _PAIR_COLORS[i % len(_PAIR_COLORS)],
                    "match_keys": [a, b], "exclude": []})
    return out


def parse_cohpcar(path: Path):
    """Parse LOBSTER 5.x COHPCAR.lobster.

    Format:
        Line 1: 'ESCALE ; pCOHP file generated by LOBSTER ...'
        Line 2: n_bonds  n_spin  n_energies  E_min  E_max  ?  (whitespace)
        Line 3: 'Average'   (header for total/avg column in data block)
        Lines 4 .. (3 + n_bonds): bond defs 'No.N:Atom1X->Atom2Y(distance)'
        Then n_energies rows of:
            E  total_pCOHP  total_iCOHP  b1_pCOHP  b1_iCOHP  b2_pCOHP  b2_iCOHP ...

    Returns:
        E : 1-D ndarray (E - E_F), eV
        bonds : list[dict], one per bond:
            { 'id': int, 'a': elem1, 'b': elem2, 'distance': float, 'pcohp': ndarray }
        Note: we flip sign so 'pcohp' = -pCOHP (bonding > 0, antibonding < 0).
    """
    lines = path.read_text().splitlines()
    # Line 1 header — skip.
    # Line 2 meta
    meta = lines[1].split()
    n_bonds = int(meta[0])      # entry count INCLUDING the leading "Average"
    n_spin = int(meta[1])
    n_energies = int(meta[2])

    bonds_meta = []  # list of {id, a, b, distance}
    iline = 2
    # 'Average' line then bond defs. LOBSTER 5.x: meta n_bonds counts Average.
    if lines[iline].strip().lower().startswith("average"):
        iline += 1
    bond_re = re.compile(
        r"No\.(\d+):\s*([A-Za-z]+)\d+->\s*([A-Za-z]+)\d+\(([\d.]+)\)")
    while iline < len(lines):
        line_stripped = lines[iline].strip()
        if not line_stripped:
            iline += 1
            continue
        m = bond_re.match(line_stripped)
        if m:
            bonds_meta.append({
                "id": int(m.group(1)),
                "a": m.group(2),
                "b": m.group(3),
                "distance": float(m.group(4)),
            })
            iline += 1
        else:
            # First non-bond line → energy block starts here.
            break
    n_bonds_actual = len(bonds_meta)

    # Parse energy block. Column layout per row:
    #   col 0 = E - E_F
    #   col 1 = total pCOHP    col 2 = total ICOHP
    #   col 3 = b1 pCOHP        col 4 = b1 ICOHP
    #   col 5 = b2 pCOHP        col 6 = b2 ICOHP
    #   ...
    # Column layout per energy row (LOBSTER), n_spin blocks each of size
    # 2*n_bonds (pCOHP,ICOHP per entry incl. the leading 'Average' = entry 0):
    #   col 0 = E ; then for spin s, entry e: pCOHP @ 1 + s*spin_block + 2*e
    # A real bond b (0-based) = file entry e=b+1 (entry 0 is 'Average').
    # We SUM over spins so n_spin=2 (AFM) gives the total pCOHP (not half).
    spin_block = 2 * n_bonds
    need_cols = 1 + n_spin * spin_block
    E = []
    cohp = [[] for _ in range(n_bonds_actual)]
    while iline < len(lines) and len(E) < n_energies:
        parts = lines[iline].split()
        iline += 1
        if len(parts) < need_cols:
            continue
        try:
            E.append(float(parts[0]))
            for b in range(n_bonds_actual):
                e = b + 1  # skip 'Average' (entry 0)
                val = sum(float(parts[1 + s * spin_block + 2 * e])
                          for s in range(n_spin))
                cohp[b].append(val)
        except (ValueError, IndexError):
            continue
    E = np.array(E)
    for b in range(n_bonds_actual):
        # Flip sign so bonding > 0 on plot x-axis.
        bonds_meta[b]["pcohp"] = -np.array(cohp[b])
    return E, bonds_meta


def parse_icohplist(path: Path):
    """Parse ICOHPLIST.lobster -> list of per-bond records {a,b,dist,icohp}.
    ICOHP is spin-summed (cols 7.. = per-spin ICOHP at E_F)."""
    recs = []
    for line in path.read_text().splitlines():
        s = line.strip()
        if not s or s.lower().startswith("cohp") or s.startswith("#") or s.startswith("LABEL"):
            continue
        parts = s.split()
        if len(parts) >= 8:
            try:
                a1 = re.sub(r"\d", "", parts[1])
                a2 = re.sub(r"\d", "", parts[2])
                dist = float(parts[3])
                icohp = sum(float(x) for x in parts[7:])  # sum spins
                recs.append({"a": a1, "b": a2, "dist": dist, "icohp": icohp})
            except (ValueError, IndexError):
                continue
    return recs


def aggregate_bond_pair(E, bonds_meta, icohp_recs, match_keys, exclude=None, dmax=None):
    """Sum -pCOHP curve + mean ICOHP across bonds matching the element pair.
    dmax (A) optionally drops long non-bonded contacts within the generator
    cutoff (e.g. P-S at >2.6 A) so curve and box match the tetrahedral bond.
    Returns (cohp_summed, icohp_box_mean, n_matched)."""
    exclude = set(exclude or [])
    target = set(match_keys)

    def ok(a, b, d):
        return ({a, b} == target and not (exclude & {a, b})
                and (dmax is None or d <= dmax))

    matched = [bm for bm in bonds_meta if ok(bm["a"], bm["b"], bm["distance"])]
    if not matched:
        return np.zeros_like(E), 0.0, 0
    summed = np.sum([bm["pcohp"] for bm in matched], axis=0)
    icv = [r["icohp"] for r in icohp_recs if ok(r["a"], r["b"], r["dist"])]
    box = float(np.mean(icv)) if icv else 0.0
    return summed, box, len(matched)


def gaussian_smooth(y, E, sigma_eV):
    """Convolve y(E) with a normalized Gaussian (sigma in eV). Uniform E grid."""
    if sigma_eV is None or sigma_eV <= 0:
        return y
    dE = abs(E[1] - E[0])
    n = max(1, int(round(4 * sigma_eV / dE)))
    x = np.arange(-n, n + 1) * dE
    k = np.exp(-0.5 * (x / sigma_eV) ** 2)
    k /= k.sum()
    return np.convolve(y, k, mode="same")


def plot_panel(ax, E, cohp, color, label, icohp_value, fermi_ref=0.0,
                xlim=None, ylim=(-12, 6)):
    """Draw one COHP panel — paper style."""
    # shade left half (antibonding) and right half (bonding) lightly
    if xlim is None:
        xmax = max(abs(cohp).max() * 1.15, 1.0)
        xlim = (-xmax, xmax)

    # filled curve on right (bonding region of -pCOHP)
    bonding_x = np.where(cohp > 0, cohp, 0)
    antibond_x = np.where(cohp < 0, cohp, 0)
    ax.fill_betweenx(E - fermi_ref, 0, bonding_x, color=color, alpha=0.55, lw=0)
    ax.fill_betweenx(E - fermi_ref, 0, antibond_x, color=color, alpha=0.55, lw=0)
    # outline
    ax.plot(cohp, E - fermi_ref, '-', color=color, lw=1.0)

    # zero vertical line
    ax.axvline(0, color='k', lw=0.7)
    # Fermi horizontal
    ax.axhline(0, color='#666', linestyle='--', lw=0.8)

    ax.set_xlim(xlim)
    ax.set_ylim(ylim)
    ax.set_xlabel(r"$-$pCOHP", fontsize=12)
    ax.tick_params(labelsize=10)

    # Antibonding (top-left) and Bonding (bottom-right) text
    ax.text(xlim[0] + (xlim[1] - xlim[0]) * 0.08,
            ylim[1] - (ylim[1] - ylim[0]) * 0.10,
            "Antibonding", fontsize=10, fontstyle='italic', color='#999', ha='left')
    ax.text(xlim[1] - (xlim[1] - xlim[0]) * 0.08,
            ylim[0] + (ylim[1] - ylim[0]) * 0.42,
            "Bonding", fontsize=10, fontstyle='italic', color='#999', ha='right')
    # E_F label
    ax.text(xlim[1] - (xlim[1] - xlim[0]) * 0.05, 0.1,
            r"$E_F$", fontsize=10, color='#666', ha='right', va='bottom')

    # Legend (label in top-right)
    leg_text = label
    ax.text(xlim[1] - (xlim[1] - xlim[0]) * 0.05, ylim[1] - (ylim[1] - ylim[0]) * 0.04,
            leg_text, fontsize=12, fontweight='bold',
            ha='right', va='top', bbox=dict(facecolor=color, alpha=0.18,
                                              edgecolor='none', boxstyle='round,pad=0.3'))

    # ICOHP box at bottom
    icohp_str = f"ICOHP = {icohp_value:.3f} eV"
    ax.text(0, ylim[0] + (ylim[1] - ylim[0]) * 0.04, icohp_str,
            ha='center', va='bottom', fontsize=11, fontweight='bold',
            bbox=dict(boxstyle="round,pad=0.4", facecolor='white',
                       edgecolor='#666', lw=0.8))

    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--lobster_dir", required=True,
                    help="dir containing COHPCAR.lobster + ICOHPLIST.lobster")
    ap.add_argument("--out_png", required=True)
    ap.add_argument("--ylim", type=float, nargs=2, default=[-12, 6])
    ap.add_argument("--preset", default="modelc", choices=list(PRESETS),
                    help="panel set: modelc (P-S/S-S/Li-S/Li-Cl) or nd (P-S/P-O/Li-S/Nd-S)")
    ap.add_argument("--panels", default=None,
                    help='override preset, e.g. "P-S,P-O,Li-S,Nd-S"')
    ap.add_argument("--smooth", type=float, default=0.10,
                    help="extra Gaussian broadening sigma (eV) on -pCOHP curves; 0=off")
    ap.add_argument("--csv", default=None,
                    help="also write energy-resolved smoothed -pCOHP table to this CSV")
    args = ap.parse_args()
    cfg_list = build_panels(args.panels) if args.panels else PRESETS[args.preset]

    work = Path(args.lobster_dir)
    cohp_path = work / "COHPCAR.lobster"
    icohp_path = work / "ICOHPLIST.lobster"
    if not cohp_path.exists() or not icohp_path.exists():
        raise SystemExit(f"missing LOBSTER files in {work}")

    E, bonds_meta = parse_cohpcar(cohp_path)
    icohp_recs = parse_icohplist(icohp_path)
    print(f"Parsed {len(bonds_meta)} bond entries × {len(E)} energy points")

    n = len(cfg_list)
    fig, axes = plt.subplots(1, n, figsize=(4 * n, 6), sharey=True)
    axes = np.atleast_1d(axes)
    curves = {}          # label -> smoothed -pCOHP (for CSV)
    icohp_box = {}
    for ax, cfg in zip(axes, cfg_list):
        cohp_sum, icohp_per_bond, nb = aggregate_bond_pair(
            E, bonds_meta, icohp_recs, cfg["match_keys"],
            cfg.get("exclude"), cfg.get("dmax"))
        cohp_s = gaussian_smooth(cohp_sum, E, args.smooth)
        curves[cfg["label"]] = cohp_s
        icohp_box[cfg["label"]] = icohp_per_bond
        print(f"  panel {cfg['label']}: matched {nb} bonds "
              f"(dmax={cfg.get('dmax')}), ICOHP/bond = {icohp_per_bond:.3f} eV")
        plot_panel(ax, E, cohp_s, cfg["color"], cfg["label"],
                    icohp_per_bond, ylim=tuple(args.ylim))
        if nb == 0:
            ax.text(0.5, 0.5, f"no {cfg['label']} bonds", transform=ax.transAxes,
                    ha='center', color='#999', fontsize=12)
    axes[0].set_ylabel(r"$E - E_F$  (eV)", fontsize=12)

    if args.csv:
        import csv as _csv
        with open(args.csv, "w", newline="") as f:
            w = _csv.writer(f)
            w.writerow([f"# energy-resolved -pCOHP (bonding>0), Gaussian sigma={args.smooth} eV; "
                        f"ICOHP(eV/bond): " + ", ".join(f"{k} {v:.3f}" for k, v in icohp_box.items())])
            w.writerow(["E_minus_EF_eV"] + [f"-pCOHP_{k.replace('–','-')}" for k in curves])
            cols = list(curves.values())
            for i, e in enumerate(E):
                w.writerow([f"{e:.4f}"] + [f"{c[i]:.5f}" for c in cols])
        print(f"→ CSV {args.csv}")

    # subplot letter labels
    for letter, ax in zip("abcdef", axes):
        ax.text(-0.10, 1.02, letter, transform=ax.transAxes,
                fontsize=16, fontweight='bold', ha='right', va='bottom')

    plt.tight_layout()
    plt.savefig(args.out_png, dpi=300, bbox_inches='tight', facecolor='white')
    print(f"\n→ {args.out_png}")


if __name__ == "__main__":
    main()
